 numpy의 여러 함수를 사용하여 ndarray의 연산에 대해 알아보자 .

In [1]:
import numpy as np

## 연산함수
- add, substract, multiply, divide

In [4]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.07207928 0.73652318 0.34170066 0.8448357  0.01777113]
 [0.73079477 0.1059902  0.43625667 0.43509957 0.93077894]
 [0.45015516 0.53824658 0.10250558 0.15588013 0.18955956]]


In [5]:
np.add(x, y) #index가 같은 element 끼리 연산 

array([[ 0.07207928,  1.73652318,  2.34170066,  3.8448357 ,  4.01777113],
       [ 5.73079477,  6.1059902 ,  7.43625667,  8.43509957,  9.93077894],
       [10.45015516, 11.53824658, 12.10250558, 13.15588013, 14.18955956]])

In [6]:
# 단, 기본적으로 shape이 다르면 에러가 발생한다. 

In [7]:
np.subtract(x, y)

array([[-0.07207928,  0.26347682,  1.65829934,  2.1551643 ,  3.98222887],
       [ 4.26920523,  5.8940098 ,  6.56374333,  7.56490043,  8.06922106],
       [ 9.54984484, 10.46175342, 11.89749442, 12.84411987, 13.81044044]])

In [8]:
np.multiply(x, y)

array([[0.        , 0.73652318, 0.68340132, 2.53450711, 0.07108452],
       [3.65397383, 0.63594122, 3.05379666, 3.48079657, 8.37701049],
       [4.50155165, 5.92071239, 1.23006699, 2.02644165, 2.65383388]])

In [9]:
#근데 일반적인 사칙연산연 경우, 연산자를 바로 쓸 수 있다. x+y, x-y, x*y, x/y

### 통계 함수
- 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [10]:
print(y)

[[0.07207928 0.73652318 0.34170066 0.8448357  0.01777113]
 [0.73079477 0.1059902  0.43625667 0.43509957 0.93077894]
 [0.45015516 0.53824658 0.10250558 0.15588013 0.18955956]]


In [11]:
np.mean(y) # y.mean()로 써도 된다.  #평균

0.4058784748387866

In [12]:
np.max(y) #가장 큰 값

0.9307789434484579

In [13]:
np.argmax(y) #가장 큰 값의 index를 flatten일 때로 가정하고 가져온다. 

9

### 집계함수
- 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [14]:
y

array([[0.07207928, 0.73652318, 0.34170066, 0.8448357 , 0.01777113],
       [0.73079477, 0.1059902 , 0.43625667, 0.43509957, 0.93077894],
       [0.45015516, 0.53824658, 0.10250558, 0.15588013, 0.18955956]])

In [16]:
np.sum(y)

6.088177122581799

In [17]:
np.cumsum(y) #해당 수까지의 누적 된 값 합. 

array([0.07207928, 0.80860246, 1.15030312, 1.99513882, 2.01290995,
       2.74370472, 2.84969492, 3.28595159, 3.72105116, 4.6518301 ,
       5.10198527, 5.64023185, 5.74273743, 5.89861756, 6.08817712])

### any, all함수
- any : 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
- all : 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [18]:
z = np.random.randn(10)
print(z)

[ 0.46709395 -0.93893042  1.20193111 -1.06003105  1.47593562 -0.42303233
  0.32644072  0.11635708  0.2818312   1.91734356]


In [19]:
z>0

array([ True, False,  True, False,  True, False,  True,  True,  True,
        True])

In [20]:
np.any(z>0)

True

In [21]:
np.all(z>0)

False

### where 함수
- 조건에 따라 선별적으로 값을 선택 가능
- 사용 예) 음수인 경우는 0, 나머지는 그대로 값을 쓰는 경우

In [22]:
z = np.random.randn(10)
print(z)

[ 0.71827658 -0.71383775 -2.04474376 -0.51845676 -0.55492414 -0.62696209
  0.10593903  0.44887045 -0.6941169   0.58963745]


In [24]:
np.where(z>0, z, 0) #where(조건, 참 일 때 값, 거짓 일 때 값)

array([0.71827658, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.10593903, 0.44887045, 0.        , 0.58963745])