# 1. Naive Bayes 실습

## 1) Gaussian Naive Bayes 실습

### 1. (Scikit-learn의 기본적인 dataset 중에 4가지 특성으로 아이리스 꽃을 분류하는 예제가 있습니다,) 데이터, 모듈 불러오기

In [1]:
from sklearn import datasets #sklearn의 데이터 불러오기
from sklearn.naive_bayes import GaussianNB #sklearn의 Gaussian Naive Bayes 모듈 불러오기

In [2]:
import pandas as pd

In [8]:
iris = datasets.load_iris() 
# from sklearn.datasets import load_iris 
#data = load_iris()
#이렇게 해도 됨. 

df_X = pd.DataFrame(iris.data)
df_Y = pd.DataFrame(iris.target)

In [9]:
df_X.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

1) data에는 각 꽃의 특성(feature)이 담겨있습니다.

2) target은 data array와 짝이 일치합니다(어떤 식인지는 모르겠지만 이어져 있는 것 같습니다). 이는 각 행이 어떤 꽃을 나타내는지를 알려줍니다.
– 0: Setosa, 1: Versicolor, 2: Virginica   <– target_names에 담겨있는 내용

3) feature_names에는 data의 특성이 무엇을 의미하는지 알려준다.

In [10]:
df_Y.head()

0
0  0
1  0
2  0
3  0
4  0

### 2. Gaussian naive bayes model fitting

In [12]:
gnb = GaussianNB()
fitted = gnb.fit(iris.data, iris.target)

y_predict = fitted.predict(iris.data) #iris.data로 predict하여 y_predict까지 해준다. 

In [13]:
y_predict[[1, 48, 51, 100]] # fitted.predict(iris.data)[[1, 48, 51, 100]] 

array([0, 0, 1, 2])

### 3. 성능 평가 
https://datascienceschool.net/view-notebook/731e0d2ef52c41c686ba53dcaf346f32/#사이킷런-패키지에서-지원하는-분류-성능평가-명령
반드시 참고하기 

사이킷런 패키지에서 지원하는 분류 성능평가 명령¶

사이킷런 패키지는 metrics 서브패키지에서 다음처럼 다양한 분류용 성능평가 명령을 제공한다.

- confusion_matrix(y_true, y_pred)
- accuracy_score(y_true, y_pred)
- precision_score(y_true, y_pred)
- recall_score(y_true, y_pred)
- fbeta_score(y_true, y_pred, beta)
- f1_score(y_true, y_pred)
- classfication_report(y_true, y_pred)
- roc_curve
- auc

In [20]:
#Confusion matrix 구하기
from sklearn.metrics import confusion_matrix

In [21]:
confusion_matrix(iris.target, y_predict) # 0인건 다 잘 맞추고, 1의 결과는 3개 잘 못 맞췄고, 2의 결과도 3개 잘 못 맞춤

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  3, 47]])

In [22]:
#accuracy_score 구하기
from sklearn.metrics import accuracy_score
accuracy_score(iris.target, y_predict)

0.96

In [25]:
#Prior 설정하기 
# Prior을 3번째 범주에 많이 줬다. 즉, 3번째 범주를 맞출 확률을 막 높이니까 잘 맞춤 (그런데, 첫 번째 범주의 경우,  [0, 33, 17])로 오류가 많았다. 
gnb2 = GaussianNB(priors = [1/100, 1/100, 98/100])
fitted2 = gnb2.fit(iris.data, iris.target)
y_predict2 = fitted2.predict(iris.data)
confusion_matrix(iris.target, y_predict2)

array([[50,  0,  0],
       [ 0, 33, 17],
       [ 0,  0, 50]])

In [27]:
# Prior을 2에 많이 줬다. 즉, 2번째 범주를 맞출 확률을 막 높이니까 잘 맞춤 (그런데, 세 번째 범주의 경우,   [ 0, 14, 36])로 오류가 많았다.
gnb2 = GaussianNB(priors = [1/100, 98/100, 1/100])
fitted2 = gnb2.fit(iris.data, iris.target)
y_predict2 = fitted2.predict(iris.data)
confusion_matrix(iris.target, y_predict2)

array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0, 14, 36]])

## 2) Multinomial naive bayes 실습

### 1. 데이터, 모듈 불러오기

In [28]:
from sklearn.naive_bayes import MultinomialNB
import numpy as np

In [35]:
X = np.random.randint(5, size = (6, 100))
y = np.array([1, 2, 3, 4, 5, 6])

### 2. Multinomial vaive bayes model fitting

In [36]:
clf = MultinomialNB()
fitted = clf.fit(X, y)

In [38]:
clf.predict(X[2 : 3])

array([3])

In [ ]:
clf = MultinomialNB