# 6. Artificial Neural Network 실습

 ### 1. 데이터 불러오기


In [4]:
X = [[0., 0.], [1., 1.]]
y = [[0, 1], [1, 1]]
#간단한 데이터 만들고

### 2. 함수 불러오기

In [2]:
from sklearn.neural_network import MLPClassifier 
#MLP : Multi Layer Perceptron (인공신경망의 다른 이름)

### 3. Multi Layer Perceptron 모델 구축

In [7]:
clf = MLPClassifier(solver = 'lbfgs', 
                    alpha = 5, 
                    hidden_layer_sizes=layer_sizes = [5, 2], 
                    random_state = 1)
#solver = 알고리즘을 통해 어떻게 해를 구한는지 이며, 'lbfgs'가 가장 많이 쓰인다. 
#hidden layer 2개, 첫 번째 hidden layer는 5개의 노드, 두 번째 hidden layer는 2개의 node

clf.fit(X, y)

MLPClassifier(activation='relu', alpha=5, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=[5, 2], learning_rate='constant',
              learning_rate_init=0.001, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=1, shuffle=True, solver='lbfgs', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

### 4. prediction

In [9]:
y_prediction = clf.predict([[2., 2.], [-1., -2.]])
y_prediction

array([[0, 1],
       [0, 1]])

In [10]:
clf.coefs_ #.coefs_ : 각 weight를 보여줌

[array([[-7.88634248e-07, -4.24800192e-06, -4.75098154e-06,
         -3.28083096e-06, -3.35728046e-06],
        [-3.87446991e-06, -9.32382210e-06, -1.46781203e-06,
         -2.38330870e-06,  3.68919564e-07]]),
 array([[ 1.62014660e-06, -7.85946500e-07],
        [ 2.33828530e-05, -3.41781186e-06],
        [-2.86928485e-06,  2.85831763e-06],
        [-5.13091936e-07, -1.77324220e-06],
        [ 1.82786052e-06,  3.57725413e-06]]),
 array([[-2.27820581e-05, -7.17405840e-06],
        [ 4.75430691e-06, -5.04990158e-06]])]

## 6-1. model의 복잡도에 따른 퍼포먼스 비교

### 1. 데이터 불러오기 or  생성하기

In [38]:
from sklearn.datasets import make_moons, make_circles,  make_classification #데이터 셋을 만들어내는 함수들
from sklearn.model_selection import train_test_split 

In [28]:
X, y = make_classification(n_features = 2, n_redundant = 0, n_informative = 2, random_state = 0, n_clusters_per_class = 1)

In [34]:
pd.DataFrame(X).head()
pd.DataFrame(y).head()

0
0  1
1  0
2  1
3  1
4  1

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 4)

### 2. 함수 불러오기

In [12]:
import numpy as np
import pandas as pd

#시각화
from matplotlib import pyplot as plt
from matplotlib.colors import ListedColormap

In [14]:

from sklearn.preprocessing import StandardScaler 
from sklearn.neural_network import MLPClassifier

### 3. Multi Layer Perceptron 모델 구축

- 설정할 parameter들을 입력

In [23]:
#모델 복잡도에 따른 퍼포먼스를 빅교하기 위해 다양한 알파값으로 Artificial Neural Network 만들어 보기 위해서 여러 알파값을 설정해 보도록 한다. 
alphas = np.logspace(-5, 3, 5)
alphas # 여기서 알파 값(모델 복잡도에 관련된 값이다.)을 하나하나 가져 올 것이다.
names = ['alpha ' + str(i) for i in alphas]
names

['alpha 1e-05', 'alpha 0.001', 'alpha 0.1', 'alpha 10.0', 'alpha 1000.0']

In [37]:
#위의 알파값을 적용시켜 볼 여러개의 classifier
classifiers = []
for i in alphas : 
    classifiers.append(MLPClassifier(solver = 'lbfgs', 
                                    alpha = i, 
                                    hidden_layer_sizes = [100, 100], 
                                    random_state = 1))

 - iterate over classifiers

In [43]:
scores = []
for name, clf in zip(names, classifiers):
    clf.fit(X_train, y_train)
    score = clf.score(X_test, y_test)
    scores.append(score)

In [44]:
scores

[1.0, 1.0, 1.0, 1.0, 0.25]

In [45]:
from sklearn.metrics import confusion_matrix