# 학습목표
   - random 서브모듈 함수를 통해 ndarray 생성하기

In [4]:
import numpy as np

### rand 함수
- [0, 1)사이의 분포로 랜덤한 ndarray 생성

In [5]:
np.random.rand(3, 4)

array([[0.76198335, 0.26538992, 0.5209354 , 0.50756892],
       [0.06570756, 0.16544293, 0.46826794, 0.04636648],
       [0.66769341, 0.00511298, 0.70918177, 0.88297671]])

### randn 함수
- n : normal distribution(정규분포)
- 정규분호로 샘플링 된 랜덤 ndarray 생성

In [6]:
np.random.randn(3, 4)

array([[-0.50354941, -0.28528475, -0.58641426,  0.91968269],
       [ 1.91479451,  0.40903195,  1.58807812,  1.19702162],
       [-0.04334039, -1.40949319,  0.38586664, -0.42791901]])

### randint 함수
- 특정 정수 사이에서 랜덤하게 샘플링

In [7]:
np.random.randint(1, 100, size = (3, 5)) #[1, 100)사이의 정수 랜덤하게 

array([[18, 18, 59, 73, 45],
       [ 2, 20, 27, 42, 29],
       [48, 70, 14, 22, 70]])

### seed 함수
- 랜덤한 값을 동일하게 다시 생성하고자 할 때 사용

In [10]:
np.random.seed(100)
#이때의 숫자는 그 값으만 선택 가능한 의미

In [12]:
np.random.rand(3, 4) #seed함수를 호출한 다음 랜덤을 호출하게 되면 다시 실행시키더라도 그 값을 변하지 않는다. 

array([[0.18532822, 0.10837689, 0.21969749, 0.97862378],
       [0.81168315, 0.17194101, 0.81622475, 0.27407375],
       [0.43170418, 0.94002982, 0.81764938, 0.33611195]])

## choice
- 주어진 1차원 ndarray로 부터 랜덤으로 샘플링 (뽑기!~!!)
-  정수가 주어진 경우, np.arrage(해당숫자)로 간주

In [13]:
np.random.choice(100, size = ())

array(14)

In [14]:
x = np.array([1,2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size = (2, 3))

array([[1.5, 1. , 3. ],
       [2. , 2. , 1.5]])

### 활률분포에 따른 ndarray 생성
- uniform : low~high사이의 값
- normal : 정규분호의 경우로, randn과 같다. 