## ndarray 데이터 형태를 바꿔보기 (reshape, flatten 등의 함수 이용)


In [2]:
import numpy as np

### ravel, np.ravel
- 다차원의 배열을 1차원으로 변경
- 'order'파라미터 
    - 'C' : row우선 변경
    - 'F' : column우선 변경

In [7]:
x = np.arange(15).reshape(3, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [14]:
temp = x.ravel() #or np.ravel(x)
print(temp)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [16]:
temp[0] = 100
print(temp)
print(x) ##즉, ravel을 쓰면 원본도 바뀐다. 

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


In [25]:
np.ravel(x, order = 'C') #array([100,   1, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14])
#가로로 쭉 먼저 펼쳐진다. 
np.ravel(x, order = 'F') #array([100,   5,  10,   1,   6,  11, 100,   7,  12,   3,   8,  13,   4,  9,  14])
#세로로 쭉 먼저 펼쳐진다. 

array([100,   5,  10,   1,   6,  11, 100,   7,  12,   3,   8,  13,   4,
         9,  14])

### flatten
- 다차원의 배열을 1차원으로 변경
- 'order'파라미터 
    - 'C' : row우선 변경
    - 'F' : column우선 변경
- ***ravel과의 차이점*** : copy를 생성하여 변경함 (즉, 원본 데이터가 아닌 복사본을 반환)

In [19]:
y = np.arange(15).reshape(3, 5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [20]:
temp = y.flatten()

In [21]:
temp[2] = 100
print(temp)
print(x) ##즉, flatten은 ravel처럼 원본은 건드리지 않는다. 

[  0   1 100   3   4   5   6   7   8   9  10  11  12  13  14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


 ### 3차원으로 한번 해보자
 

In [26]:
x = np.arange(30).reshape(2, 3, 5)
print(x)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [27]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

 ### 주의사항 
 
- reshape하는 결과가 그 전의 결과의 원소 개수와 같아야지만 가능하다. 
- 계산의 편리성을 위해 나머지 값들이 fix가 되어 있으면 나머지 하나는 -1로 하면 자동으로 계산되어 들어간다, 