# 7. broadcasting 이해 및 사용하기
broadcasting
- shape이 같은 ndarray에 대한 연산은 각 원소별로 진행이 되는데, 
- 다른 경우, 브로드 캐스팅으로 shape을 맞춘 후 연산을 진행한다. 

In [2]:
import numpy as np

### 1) shape가 같은 경우 연산

In [3]:
x = np.arange(15).reshape(3, 5)
y = np.random.randn(15).reshape(3, 5)

In [5]:
print(x)
print(y)
x+ y

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0.18973466 -0.95427445  0.29300783  0.39065379  0.45059786]
 [-0.42436533  0.20483025  0.80173543  0.13029984  0.52876051]
 [-0.14009854 -1.11128235 -1.23257176  2.27267544  0.12308727]]


array([[ 0.18973466,  0.04572555,  2.29300783,  3.39065379,  4.45059786],
       [ 4.57563467,  6.20483025,  7.80173543,  8.13029984,  9.52876051],
       [ 9.85990146,  9.88871765, 10.76742824, 15.27267544, 14.12308727]])

### 2) shape가 다른 경우
#### 1. Scala(상수)와의 연산

In [6]:
x+2 #모든 원소에 하나하나 적용된다.

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

#### 2. Shape이 다른 경우 연산

In [8]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)

print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]


In [9]:
a+b #rule : 

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [10]:
c = np.arange(1000, 1004)

In [11]:
a+c #에러가 난다. 

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [13]:
print(a.shape)
print(b. shape)
print(c. shape) 

(4, 3)
(3,)
(4,)


In [ ]:
broadcasting은 뒤에 나오는 차원부터 비교한다. 그래서 a의 3과 b의 3이 일치하니까 broadcasting으로 연산이 되는거고, 
a의 3과 c의 4는 맞지 않으니까 broadcasting이 안되고 에러가 난다 